---
title: 
output: 
  html_document:
    df_print: paged
---

# Contact Information

- Phone: +1 (617) 959-2232
- Email: merveillekoissi.savi@gmail.com
- LinkedIn: [Koissi Savi](linkedin.com/in/Koissi Savi)
- GitHub: [SaviKoissi](github.com/SaviKoissi)

# Profile

- Strong leadership and collaborative research.
- Experience in multidisciplinary research.
- Rich experience in mathematical modeling and computer simulation.
- Experience teaching statistics, mathematics.
- Experience in computational oncology and bioinformatics.

# Education

- **PhD, Theoretical Ecology (Magna Cum Laude)**
  - University of Bonn, Germany, NRW
  - Jul. 2017 – Feb. 2022

- **M.Sc, Statistics (First-class honor)**
  - University of Abomey-Calavi, Benin, Lit.
  - Oct. 2014 – Dec 2016

- **M.Sc, Environmental Sci. (First-class honor)**
  - University of Abomey-Calavi, Benin, Lit.
  - Oct. 2010 – Dec 2011

- **B.Sc, Agricultural Sciences**
  - University of Abomey-Calavi, Benin, Lit.
  - Sep. 2007 – Sep. 2010

- **B.Sc, Mathematics Physics and Biology**
  - University of Abomey-Calavi, Benin, Lit.
  - Sep. 2004– Sep. 2007

# Selected Research Experience

## Postdoc Fellowship, Dana Farber Cancer Institute/Harvard School of Medicine

- **Functional Genomics on RUNX1**
  - Access the functional effect of homozygous pathogenic RUNX1 mutations.

- **Machine Learning and Deep Learning**
  - Develop a learning pipeline that predicts the functional outcome of unknown variants from a single nucleotide mutations.

- **Bioinformatics and Data Analysis**
  - Assessing the factors that underpin the high prevalence of clonal hematopoiesis in sickle cell patients.

## Postdoc Fellowship, T.H. Chan Harvard School of Public Health

- **Differential Privacy and Metapopulation Models**
  - Access the impact of differential privacy mechanics on epidemiological models using computer simulation.

- **Assessment of Epidemiological Metrics in the Case of Disasters**
  - Develop the methodology and new metrics that account for mobility data in the case of disaster.

- **Develop Modular Applications**
  - Develop a modular software quantifying the impact of noisy data on the metapopulation model. Development and Management of a web-deployed dashboard producing actionable reports after a disaster denoted ReadyMapper.

## Junior Researcher, University of Bonn

- **System Modelling and Network Analysis**
  - Expert meeting and group modeling of the driving factors underlining the persistence of malaria in urban settings using Accra (Ghana) as a case study.

- **Statistical Modeling and Machine Learning**
  - Investigation of trends and identification of clustering in malaria epidemics in Ghana using the multilevel model and geostatistics methods.

- **Mathematical Modelling and Computer Simulation**
  - Develop a patch Eulerian model that informs the dynamics of malaria in urban settings. Study of the stability of the mathematical model. Calibrate the mathematical model with real data using partially observed Markov methods. Simulated community behavior and mobility using the mechanistic model developed. Assess the robustness of the developed mechanistic model.

- **Mathematical Modeling**
  - Formulation and refinement of maths-prone models with an emphasis on malaria-model-based human mobility.

# Most Recent Teaching Experience

- **Center for Development Research**
  - Jan.; Mar. & Nov. 2021 University of Bonn, Germany, NRW
  - Introduction to Mathematical Epidemiology
  - Introduction to Mathematical Biology

# Awards, Scholarships, Fellowships, and Grants

- ”GetFinished” Scholarship, University of Bonn, 2020
- Santa Fe Institute Fellowship, 2019
- System Dynamics Society Student Award, 2018
- Rufford Second Grant, 2017
- Rufford Small Grant, 2015

# Certifications

- Bioinformatics Core, Harvard Catalyst (Nov. 2022)
- Certificate for Human Research, CITI (Dec. 2022)
- Data Science, IBM, (In Progress)
- Epidemics - the Dynamics of Infectious Diseases, The Pennsylvania State University, (In Progress)
- Systems Thinking In Public Health, Johns Hopkins University, Apr. 2018

# Selected Conferences, Presentations, and Talks

- Predicting Telomere Elongation using Machine Learning model, Dana Farber Cancer Institute, Medical Oncology (MA, USA), Sep. 2023;
- Assess the impact of insecticide-treated bed nets on urban malaria epidemics in Accra, Ghana using mathematical modeling, Georgia Southern University, Biostatistics, Epidemiology and Environmental Health, (GA, USA), Sep. 2022 ;
- Exploring the complexity of malaria transmission in Ghana; Harvard T.H. Chan School of Public Health Center for Communicable Disease Dynamics Department of Epidemiology (MA, USA), Dec. 2019
- From an individual mental model to a malaria system dynamic model: A step toward the elimination of malaria in an urban setting in Accra; 16th International Conference on Urban Health, ICUH (Xiamen, China), Nov. 2019
- Host-Vector-Parasite System Dynamics Analysis for Enhancing Malaria Control in Accra, Ghana; The 36th International Conference of the System Dynamics Society (ReykjavLk, Iceland), Aug. 2018

# Technical Skills and Application Developed

- Computer languages: R, SAS, Python, SQL, Bash, Shell, Docker, WDL
- Cloud Computing: AWS, Google Cloud, Microsoft Terra, IBM-DB2
- R plug and play application: DP Metapopulation
- R shiny app: malDecision
- R package development REcoToxi, In progress
- Python and shell-based dashboard ReadyMapper
- Language: English: professional proficiency French: native German: beginner

# Selected Services to the Scientific Community

- Reviewer for Sustainability (2023)
- Reviewer for Pathogen (2023)
- Reviewer for Frontier Infectious Diseases, epidemiology and Prevention (2023)
- Reviewer Editor for Frontier Malaria (2023)
